### PR TITLE
AccountWithSigProvider

### PR DESCRIPTION
**Pull request by qftgtr**
Class `AccountWithSigProvider` inherits from `Account`. It requires an address and a signature provider (instead of a private key) to initialize. An example signature provider is

``` js
const sigProvider = address => {
  return async tx => {
    // Can show a prompt window to notify users what transaction is requesting for signature
    const privateKey = await getPrivateKeyFromExternal(address);
    tx.sign(privateKey);
    return tx;
  };
}
```

An alternative is sending `tx` to the external private key storage for signing and only the signature is returned. Therefore, the private key is never disclosed.

`AccountWithSigProvider` also has methods `signTransaction()` and `signMessage()` but now they use the signature provider for the signing process. The two methods are asynchronous because the signature provider needs to be asynchronous.

With `AccountWithSigProvider`, it is possible to use the sdk with an external private key storage.

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/49)

### CODE REVIEW

**Comment by GeekBerry** [comment]
有无可能将  sigProvider(address) =>AddressSignProvider 看作是一种 "PrivateKey", 然后重载 Account constructor 以支持将 AddressSignProvider 作为初始化参数

**Comment by qftgtr** [comment]
> 有无可能将 sigProvider(address) =>AddressSignProvider 看作是一种 "PrivateKey", 然后重载 Account constructor 以支持将 AddressSignProvider 作为初始化参数

可以，这样的话需要将`signTransaction()`和`signMessage ()`两个方法都改成移步的

**Comment by GeekBerry** [comment]
> > 有无可能将 sigProvider(address) =>AddressSignProvider 看作是一种 "PrivateKey", 然后重载 Account constructor 以支持将 AddressSignProvider 作为初始化参数
> 
> 可以，这样的话需要将`signTransaction()`和`signMessage ()`两个方法都改成移步的

* 准确来说两个方法有可能返回 Promise 即可, 方法本身不一定要 async 装饰.
* signProvider 是去调用 RPC 吗? RPC 已经公网上实现了吗, 还是某个封装的语法糖?

**Comment by resodo** [comment]
___
*[src/AccountWithSigProvider.js, line 7 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/49#-MB3N8ww3tVXJkv8aFHg:-MB3N8ww3tVXJkv8aFHh:bxb31tr) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/8cb152f6c2b74fd5abde9b2fddedb4bc65dbe068/src/AccountWithSigProvider.js#L7)):*
> ```JavaScript
> class AccountWithSigProvider extends Account {
>   /**
>    * Create an account that sign using a signature provider.
> ```

Looks good, this feature sounds reasonable and I do support to involve it. Besides the implementation details suggested by @GeekBerry, we need to let anyone can implement his own sigProvider easily. For now, the interfaces and examples of sigProvider are needed, not only in unit tests but in documents and examples.

Could you add them in?

**Comment by resodo** [comment]
And I suppose there should be already some protocols to handle the remote sign stuff? Maybe we can follow the mature convention if there is any.

> _[src/AccountWithSigProvider.js, line 7 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/49#-MB3N8ww3tVXJkv8aFHg:-MB3N8ww3tVXJkv8aFHh:bxb31tr) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/8cb152f6c2b74fd5abde9b2fddedb4bc65dbe068/src/AccountWithSigProvider.js#L7)):_
> 
> > ```js
> > class AccountWithSigProvider extends Account {
> >   /**
> >    * Create an account that sign using a signature provider.
> > ```
> 
> Looks good, this feature sounds reasonable and I do support to involve it. Besides the implementation details suggested by @GeekBerry, we need to let anyone can implement his own sigProvider easily. For now, the interfaces and examples of sigProvider are needed, not only in unit tests but in documents and examples.
> 
> Could you add them in?

**Comment by qftgtr** [comment]
> > > 有无可能将 sigProvider(address) =>AddressSignProvider 看作是一种 "PrivateKey", 然后重载 Account constructor 以支持将 AddressSignProvider 作为初始化参数
> > 
> > 
> > 可以，这样的话需要将`signTransaction()`和`signMessage ()`两个方法都改成移步的
> 
> * 准确来说两个方法有可能返回 Promise 即可, 方法本身不一定要 async 装饰.

意思是，如果异步返回Promise，非异步直接返回结果？

> * signProvider 是去调用 RPC 吗? RPC 已经公网上实现了吗, 还是某个封装的语法糖?

`signProvider`在PR的描述中给了一个例子，我可以将例子加到docs和examples里。

**Comment by qftgtr** [comment]
> And I suppose there should be already some protocols to handle the remote sign stuff? Maybe we can follow the mature convention if there is any. Do you have any ideas? @qftgtr
> 
> > _[src/AccountWithSigProvider.js, line 7 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/49#-MB3N8ww3tVXJkv8aFHg:-MB3N8ww3tVXJkv8aFHh:bxb31tr) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/8cb152f6c2b74fd5abde9b2fddedb4bc65dbe068/src/AccountWithSigProvider.js#L7)):_
> > > ```js
> > > class AccountWithSigProvider extends Account {
> > >   /**
> > >    * Create an account that sign using a signature provider.
> > > ```
> > 
> > 
> > Looks good, this feature sounds reasonable and I do support to involve it. Besides the implementation details suggested by @GeekBerry, we need to let anyone can implement his own sigProvider easily. For now, the interfaces and examples of sigProvider are needed, not only in unit tests but in documents and examples.
> > Could you add them in?

Sure, I can add more description to the docs and examples.

**Comment by GeekBerry** [comment]
* 希望 SigProvider 重命名为 SignProvider 因为全局没有 "sig" 标识符, 而均用 "sign" 表示签名的动词.
* SDK 中 Provider 指 BaseProvider 及其子类, 目前仅含 HttpProvider, SignProvider 是否还有更好的名称?
* 如果 SignProvider 是通过 RPC 实现, 希望能通过 Conflux 调用 RPC 获取所需数据, 与 default 机制保持一致. 不建议采用柯里化和面向对象的风格混合使用

**Comment by resodo** [comment]
> * RPC
1. agree
2. How about signer or remoteSigner?
3. I'm not sure they are going to implement it via RPC or other ways

**Comment by resodo** [comment]
> * 希望 SigProvider 重命名为 SignProvider 因为全局没有 "sig" 标识符, 而均用 "sign" 表示签名的动词.
> * SDK 中 Provider 指 BaseProvider 及其子类, 目前仅含 HttpProvider, SignProvider 是否还有更好的名称?
> * 如果 SignProvider 是通过 RPC 实现, 希望能通过 Conflux 调用 RPC 获取所需数据, 与 default 机制保持一致. 不建议采用柯里化和面向对象的风格混合使用

agree
How about signer or remoteSigner?
I'm not sure they are going to implement it via RPC or other ways

**Comment by yqrashawn** [comment]
Why not just call cfx_sign with the current provider when there’s no private key provided like cfx_sendTransaction?

**Comment by qftgtr** [comment]
> * 希望 SigProvider 重命名为 SignProvider 因为全局没有 "sig" 标识符, 而均用 "sign" 表示签名的动词.
> * SDK 中 Provider 指 BaseProvider 及其子类, 目前仅含 HttpProvider, SignProvider 是否还有更好的名称?
> * 如果 SignProvider 是通过 RPC 实现, 希望能通过 Conflux 调用 RPC 获取所需数据, 与 default 机制保持一致. 不建议采用柯里化和面向对象的风格混合使用

It is usually named as `signatureProvider` since the main purpose of it is to provide signatures. I use `sig` for brevity but maybe it's confusing. This `signatureProvider` is actually not relevant to `HttpProvider`. To avoid misinterpretation, I agree with @resodo that we could just use `signer`.

The `signer` has nothing to do with the RPC. The design of it is to allow separation of the SDK and sensitive credentials. For example, dApps should be able to include the SDK without using any private keys, because expose private keys to each individual dApps would increase the risk of leaking them. Private keys are only stored in dedicated storage, such as MetaMask-like extension, mobile wallet, or cold wallet. The key storage will implement the `signatureProvider` or `signer` and provide it to the SDK. The SDK will only construct the transaction and give it to the key storage for the signing process. Once the signature is returned, the SDK will also be responsible to push the transaction to Conflux network.

**Comment by qftgtr** [comment]
@resodo @GeekBerry 

The PR is updated with the following changes:

- Rename `sigProvider` to `signer` and `signerCollection` to avoid confusion
- Allow creating an Account with an address (or a pubkey) together with the `signerCollection`
- `signTransaction` & `signMessage` are async now
- Tests are updated
- Docs are updated
- Examples are updated

I would recommend changing `signTransaction` & `signMessage` to async because possible returns should be of the same type. If in one case it returns a promise, I would recommend that it should always return a promise. I know this will change the API and would affect apps that already using the SDK, but I think it's better to keep it clean and change it now before the mainnet launch.

**Comment by GeekBerry** [comment]
分析了下需求, 要求 SDK 能接受一个函数进行签名, 以不向 SDK 暴露 privateKey 对吧?
* 是否可以理解为要求 Transaction 和 Message 能接受一个函数 singer 对交易进行签名.

```
@param hash {string|Buffer} - Hex64 or buffer32
@return {r,s,v}
- r {string|Buffer} Hex64 or buffer32
- s {string|Buffer} Hex64 or buffer32
- v {number}

async function singer(hash)
```

singer 可以由 address 和 signerCollection 绑定而成

* singer 必须是异步的吗? 是不是为了兼容远程签名的可能性?

**Comment by GeekBerry** [comment]
请问您熟悉 ethers.js 吗, 它是如何解决这类问题, 我们是否可以借鉴

**Comment by qftgtr** [comment]
ethers.js是定义了一个抽象类[`Signer`](https://docs.ethers.io/v5/api/signer/#Signer)，其中有`signMessage()`和`signTransaction()`方法（都是异步的）。[`Wallet`](https://docs.ethers.io/v5/api/signer/#Wallet)类继承`Signer`类，需要通过一个私钥来创建`Wallet`实例，之后会使用私钥完成`signMessage`和`signTransaction`中的签名操作。`Wallet`类其实和目前conflux sdk中的`Account`类非常类似。如果希望通过第三方应用进行签名，需要自己实现`Signer`的另一个子类，包括自己实现`signMessage()`和`signTransaction()`方法。

我目前这个PR相当于让`Account`类同时实现了ethers.js的`Wallet`类和支持第三方签名的部分。基于现有的`Account`，我觉得简单的方式是，允许创建`Account`实例时提供一个`signerCollection`，`constructor`中根据输入的地址，得到对应的`signer`。使用`signerCollection`的好处是，只需要实现这一个函数，即可创建不同地址的各个`Account`。

关于上面的另外两个问题：

> 是否可以理解为要求 Transaction 和 Message 能接受一个函数 signer 对交易进行签名.

通常不是将`signer`函数传给`Transaction`和`Message`，而是相反，把`Transaction`和`Message`传给`signer`

> signer 必须是异步的吗? 是不是为了兼容远程签名的可能性?

是的，因为签名过程本身很有可能是异步的，包括连接第三方钱包，请求用户确认等。ethers.js也是这样设计的。。

**Comment by GeekBerry** [comment]
看来这里面学问不小.
我刚才在群里也接受了Account 实现 sendTransaction 的建议, 将控制权交给 Account 实例, 所以通过继承 Account 实现 signer 的思路是对的.
下一步我会修改 Account , 因为还有其他事, 从修改到发吧预计要一两周, 请问您是否急着用此功能?

**Comment by qftgtr** [comment]
好的，不急，我们可以先用自己的fork

**Comment by GeekBerry** [comment]
对 Account 和 sendTransaction 进行重构, 您可以评审下是否符合需求, 或有什么建议

分支: https://github.com/Conflux-Chain/js-conflux-sdk/tree/dev
用例: https://github.com/Conflux-Chain/js-conflux-sdk/tree/dev/example
主要修改: https://github.com/Conflux-Chain/js-conflux-sdk/pull/71/files

**Comment by qftgtr** [comment]
> 对 Account 和 sendTransaction 进行重构, 您可以评审下是否符合需求, 或有什么建议
> 
> 分支: https://github.com/Conflux-Chain/js-conflux-sdk/tree/dev
> 用例: https://github.com/Conflux-Chain/js-conflux-sdk/tree/dev/example
> 主要修改: https://github.com/Conflux-Chain/js-conflux-sdk/pull/71/files

看了一下，没什么问题，我们可以自己重载`BaseAccount`来实现第三方签名

**Comment by GeekBerry** [comment]
我们发布了 js-conflux-sdk 1.0.0, 其中实现了[Account](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/src/wallet/Account.js) 将 signTransaction 和 signMessage 改为了 async.
还实现了 [Wallet](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/src/wallet/Wallet.js) 用于[管理 Account](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/test/wallet.test.js).
用户可以继承 Account 并使其能被 Wallet 管理, 在发送交易时`from`字段填入发送者address, sdk 会帮你在 wallet 中[找到相应account 并进行签名](https://github.com/Conflux-Chain/js-conflux-sdk/blob/d13d6938776f69a52b6b7b92fa4d06c1e2da3a36/src/Conflux.js#L821)

**Comment by GeekBerry** [comment]
由于版本更新较快, 您的 PR 和当前版本差距较大, 如有需要, 建议您基于现在版本修改或重新提出 PR.

**Pull request closed without merging**
