### PR TITLE
Add support for personal_sign.

### PR DESCRIPTION
**Pull request by Pana**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136)

### CODE REVIEW

**Review by yqrashawn — APPROVED** [review]

**Review by yqrashawn — APPROVED** [review]

**Comment by Thegaram** [comment]
Looks good. My only concern is compatibility with Conflux Portal that we discussed before.

**Review by yqrashawn — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Thegaram and @wangdayong228)

**Review by wangdayong228 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136)* status: all files reviewed, 2 unresolved discussions (waiting on @Thegaram and @wangdayong228)

___
*[src/PersonalMessage.js, line 71 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136#-Mg3qrun60zv5kcpyP_u:-Mg3qrun60zv5kcpyP_v:b-libpf4) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/48eb9d04c99101049b3b9191f40d28127ac0e5e1/src/PersonalMessage.js#L71)):*
> ```JavaScript
>     const v = parseInt(signature.slice(130), 16) - 27;
>     signature = signature.slice(0, 130) + format.hex(v).slice(2);
>     const messageHex = isHexString(message) ? message : format.hex(Buffer.from(message));
> ```

How to judge user's purpose of message is "string" or "hex" ? Suggest only support Buffer or hexstring
___
*[src/PersonalMessage.js, line 77 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136#-Mg3qtbp62WwsWCSDd3x:-Mg3qtbp62WwsWCSDd3y:bf8oz0t) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/48eb9d04c99101049b3b9191f40d28127ac0e5e1/src/PersonalMessage.js#L77)):*
> ```JavaScript
> 
>   constructor(message) {
>     const msgBuf = isHexString(message) ? format.hexBuffer(message) : Buffer.from(message);
> ```

same to above

**Review by wangdayong228 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Thegaram)

**Review by Pana — COMMENTED** [review]
For now, developers show choose different methods to verify the CIP-23 signature and portal personal sign signatures

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136#-:-Mg3vqDM60VNXl7AnlMO:bzb0g62)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Thegaram)

**Review by Pana — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Thegaram)

___
*[src/PersonalMessage.js, line 71 at r1](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/136#-Mg3qrun60zv5kcpyP_u:-Mg4-wwe3h9TUPdh6By8:b-w8315b) ([raw file](https://github.com/conflux-chain/js-conflux-sdk/blob/48eb9d04c99101049b3b9191f40d28127ac0e5e1/src/PersonalMessage.js#L71)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

How to judge user's purpose of message is "string" or "hex" ? Suggest only support Buffer or hexstring
</blockquote></details>

According to portal or metamask's implementation, both string and hex  is supported, so here is needed

**Pull request merged**
