### PR TITLE
add wechat miniprogram support (http/ws)

### PR DESCRIPTION
**Pull request by yiheyang**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/184)

### CODE REVIEW

**Review by wangdayong228 — COMMENTED** [review]
I think the better way is create a wechat provider in an independent repo and creat Conflux instance use the wechat provider

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/184#-:-MtrjU9EEKbFeOaejE6l:b-5lzze5)* status: 0 of 4 files reviewed, all discussions resolved

**Comment by yiheyang** [comment]
> I think the better way is create a wechat provider in an independent repo and creat Conflux instance use the wechat provider
> 
> > _[Reviewable](https://reviewable.io/reviews/conflux-chain/js-conflux-sdk/184#-:-MtrjU9EEKbFeOaejE6l:b-5lzze5)_ status: 0 of 4 files reviewed, all discussions resolved

I don't think so.
Basically, adding wechat support is only a matter of adapting a compatible connection part working under the wechat miniprogram environment. Meanwhile, all the provider functions are still working fine without any modification and there's no need to write them again in a whole new provider.

**Comment by Pana** [comment]
Yes agree with @wangdayong228 it's better to release a standalone WeChat provider, then can be config in Conflux option to use WeChat provider.
Because if there is a new environment like WeChat for example Alipay or Paypal, then the code will be unmaintainable.

**Comment by Pana** [comment]
Added in PR 186

**Comment by yiheyang** [comment]
No websocket support seen in PR 186. @Pana

**Pull request closed without merging**
